apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-node-app
  labels:
    app: hello-world-node-app
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-node-app
  template:
    metadata:
      labels:
        app: hello-world-node-app
    spec:
      containers:
      - name: hello-world-node-app
        image: iamnk007/hello-world-node-app:c52d8ccc86c9dd7a4afcde3e2468b92a876f78af
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
