name: CI - Build and Update Manifest for ArgoCD

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: hello-world-node-app
  DOCKERHUB_REPO: iamnk007/hello-world-node-app
  DEPLOYMENT_FILE: Kubernetes/deployment.yaml

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build and push image
      - name: Build and Push Docker Image
        id: build
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE=${{ env.DOCKERHUB_REPO }}:$IMAGE_TAG

          echo "Building image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # 4️⃣ Update Deployment YAML with new image tag
      - name: Update deployment manifest
        run: |
          sed -i "s|image: .*|image: $IMAGE|g" $DEPLOYMENT_FILE
          cat $DEPLOYMENT_FILE

      # 5️⃣ Commit and push updated YAML back to master
      - name: Commit updated manifest
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add $DEPLOYMENT_FILE
          git commit -m "Update image to $IMAGE [skip ci]" || echo "No changes to commit"
          git push origin master
